---

- name: deploy kernel configuration on host
  ansible.builtin.copy:
    src: files/etc/sysctl.d/
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: '0640'
  notify: reboot host if necessary
  become: True
