---

- name: upgrade distribution
  ansible.builtin.apt:
    upgrade: dist
    update_cache: True
  register: _apt_dist-upgrade
  become: True

- name: reboot host if necessary
  ansible.builtin.reboot:
  when: _apt_dist-upgrade.changed
  become: True
