---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: dns-allow
spec:
  order: 100
  selector: all()
  egress:
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 53
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-nodeport-ingress
spec:
  order: 120
  selector: has(kubernetes-host)
  preDNAT: true
  applyOnForward: true
  ingress:
    - action: Allow
      destination:
        selector: role == "service"
