---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-all
spec:
  ingress:
  - action: Allow
    destination: {}
    source: {}
  egress:
  - action: Allow
    destination: {}
    source: {}
  order: 10
  selector: all()
  types:
  - Egress
  - Ingress