---

- name: initialize kubernetes cluster
  shell: >-
    kubeadm init --apiserver-advertise-address={{ ansible_host }} \
    --apiserver-cert-extra-sans={{ ansible_host }}  \
    --node-name {{ inventory_hostname }} \
    --pod-network-cidr={{ ansible_host.split(".")[0] }}.{{ ansible_host.split(".")[1] }}.0.0/16
  args:
    executable: /bin/bash
  tags: master
  become: True

- name: install calico network
  shell: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
  args:
    executable: /bin/bash
  tags: master

- name: join cluster command
  shell: kubeadm token create --print-join-command
  args:
    executable: /bin/bash
  register: join_command
  tags: master
  become: True

- name: save command in temporary file
  lineinfile:
    path: "/tmp/{{ client_id }}.sh"
    line: "{{ join_command.stdout }}"
    create: True
  delegate_to: localhost
  tags: master
  become: True
