---

- name: create nfs-group
  group:
    name: nfs-group
    state: present
  tags: nfs
  become: True

- name: create data directory
  file:
    path: /data
    state: directory
    owner: root
    group: nfs-group
    mode: "2770"
  tags: nfs
  become: True

- name: create filesystem on seperate disk
  filesystem:
    fstype: ext4
    dev: /dev/sdb
  tags: nfs
  become: True

- name: mount partition on filesystem
  mount:
    src: /dev/sdb1
    path: /data
    state: mounted
    fstype: ext4
  tags: nfs
  become: True

- name: install nfs packages
  apt:
    name: nfs-kernel-server
    state: present
  tags: nfs
  become: True

- name: add network to exports
  lineinfile:
    line: "/data {{ ansible_host.split('.')[0] }}.{{ ansible_host.split('.')[1] }}.0.0/16(rw,async,no_root_squash,no_subtree_check)"
    path: /etc/exports
    create: True
  tags: nfs
  become: True

- name: start nfs server
  service:
    name: nfs-server
    enabled: True
    state: started
  tags: nfs
  become: True