---

- name: add kubernetes key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags: kubernetes
  become: True

- name: add kubernetes repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
  tags: kubernetes
  become: True

- name: install kubernetes packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  loop: "{{ _kubernetes_packages }}"
  tags: kubernetes
  become: True

- name: install calicoctl
  get_url:
    url: "https://github.com/projectcalico/calico/releases/download/{{ calico_version }}/calicoctl-linux-amd64"
    dest: /usr/local/bin
    mode: "0555"
  tags: kubernetes
  become: True

- name: renaming calico binaries
  shell: mv /usr/local/bin/calicoctl-linux-amd64 /usr/local/bin/calicoctl
  args:
    executable: /bin/bash
  tags: kubernetes
  become: True

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: "KUBELET_EXTRA_ARGS=--node-ip={{ ansible_host }}"
    create: True
  tags: kubernetes
  become: True

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: True
    state: restarted
  tags: kubernetes
  become: True