---

- name: deploy kernel configuration on host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: '0640'
  with_fileglob: files/etc/sysctl.d/*
  register: _sysctld_files
  become: True

- name: reboot host if necessary
  ansible.builtin.reboot:
  when: _sysctld_files.changed
  tags: system_security
  become: True
