---

- name: add svcansible to wheel group
  ansible.builtin.user:
    name: svcansible
    groups: wheel
    append: True
  become: True

- name: require wheel membership to use 'su'
  community.general.pamd:
    name: su
    type: auth
    control: sufficient
    module_path: pam_rootok.so
    new_type: auth
    new_control: required
    new_module_path: pam_wheel.so
    module_arguments: 'use_uid'
    state: after
  become: True
