---

- name: initialize kubernetes cluster
  shell: >-
    kubeadm init --apiserver-advertise-address={{ ansible_host }} \
    --apiserver-cert-extra-sans={{ ansible_host }}  \
    --node-name {{ inventory_hostname }} \
    --pod-network-cidr={{ ansible_host.split(".")[0] }}.{{ ansible_host.split(".")[1] }}.0.0/16
  args:
    executable: /bin/bash
  when: cloud_function == "master"
  tags: cluster
  become: True

- name: create svcansible kubernetes config folder
  file:
    path: /home/svcansible/.kube
    state: directory
  tags: cluster

- name: copy kubernetes config in svcansible config folder
  copy:
    remote_src: True
    src: /etc/kubernetes/admin.conf
    dest: /home/svcansible/.kube/config
    owner: svcansible
    group: ansible
  tags: cluster
  become: True

- name: install calico network
  shell: >-
    kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml \
    && kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml
  args:
    executable: /bin/bash
  tags: cluster

- name: join cluster command
  shell: kubeadm token create --print-join-command
  args:
    executable: /bin/bash
  register: join_command
  when: cloud_function == "master"
  tags: cluster
  become: True

- name: debug join command
  debug:
    var: join_command

- name: save command in temporary file
  lineinfile:
    path: "/tmp/{{ client_id }}.sh"
    line: "{{ join_command.results[0].stdout }}"
    create: True
  delegate_to: localhost
  when: cloud_function == "master"
  tags: cluster
  become: True

- name: copy join command on workers
  copy:
    src: "/tmp/{{ client_id }}.sh"
    dest: /tmp/join_command.sh
  when: cloud_function == "worker"
  tags: cluster
  become: True

- name: remove command file on localhost
  file:
    path: "/tmp/{{ client_id }}.sh"
    state: absent
  delegate_to: localhost
  tags: worker
  become: True

- name: launch joining command on workers
  shell: bash /tmp/join_command.sh
  args:
    executable: /bin/bash
  when: cloud_function == "worker"
  tags: worker
  become: True

- name: remove command file on workers
  file:
    path: /tmp/join_command.sh
    state: absent
  when: cloud_function == "worker"
  tags: worker
  become: True
