---

- name: install apt dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  loop: "{{ _apt_dependencies }}"
  tags: system
  become: True

- name: disable swap
  shell: swapoff -a
  args:
    executable: /bin/bash
  when: ansible_swaptotal_mb > 0
  tags: system
  become: True

- name: remove swap fs
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop: "{{ _swap_fs }}"
  tags: system
  become: True

- name: install containerd
  apt:
    name: containerd
    state: present
  tags: system
  become: True
