---

- name: install apt dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  loop: "{{ _apt_dependencies }}"
  tags: system
  become: True

- name: disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0
  tags: system
  become: True

- name: remove swap fs
  ansible.builtin.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop: "{{ _swap_fs }}"
  tags: system
  become: True

- name: install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
  tags: system
  become: True

- name: add modules for containerd
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter
    create: True
    owner: root
    group: root
  tags: system
  register: _containerd_modules
  become: True

- name: modprobe additionnal modules
  ansible.builtin.shell: modprobe overlay && modprobe br_netfilter
  args:
    executable: /bin/bash
  when: _containerd_modules.changed
  tags: system
  become: True

- name: add system configuration for kubernetes
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    create: True
    owner: root
    group: root
  tags: system
  register: _sys_config
  become: True

- name: apply system configuration
  ansible.builtin.shell: sysctl --system
  args:
    executable: /bin/bash
  when: _sys_config.changed
  tags: system
  become: True

- name: set default containerd config
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  args:
    executable: /bin/bash
  tags: system
  become: True

- name: add cgroups configuration for containerd
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    search_string: "[plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.runc.options]"
    line: "          [plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.runc.options]\n            SystemdCgroup = true"
    firstmatch: True
  tags: system
  become: True

- name: restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted
  tags: system
  become: True
