---

_apps_deploying:
  - name: mariadb
    containers:
      - image: mariadb:10.3
        envVars:
          - name: MYSQL_ROOT_PASSWORD
            value: MotDePasseEnClair!
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress
          - name: MYSQL_PASSWORD
            value: epsi2022
        volumes:
          - path: /var/lib/mysql
        ports:
          - containerPort: 3306

  - name: wordpress
    replicas: 2
    exposed: True
    containers:
      - image: wordpress:latest
        envVars:
          - name: WORDPRESS_DB_HOST
            value: mariadb-service
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: epsi2022
        volumes:
          - name: wordpress-site
            path: /var/www/html
        ports:
          - containerPort: 80
            nodePort: 30000
    rules:
      egressRules:
        - ports: 3306
          allowTo: mariadb-service
