---

_apps_deploying:
  - name: mysql
    containers:
      - image: msql:latest
        envVars:
          - name: MYSQL_USER
            value: myuser
        volumes:
          - path: /var/lib/mysql
        ports:
          - containerPort: 3306
    rules:
      ingressRules:
        - ports: 3306
          allowFrom: wordpress-service

  - name: wordpress
    containers:
      - image: wordpress:latest
        replicas: 2
        envVars:
          - name: MYSQL_URL
            value: mysql-service
          - name: MYSQL_USER
            value: myuser
        volumes:
          - name: wordpress-site
            path: /var/www/html
        ports:
          - containerPort: 80
            clusterPort: 8080

  - name: 3cx
    containers:
      - image: farfui/3cx:18.0.2.314
        volumes:
          - path: /mnt/backup
            name: 3cx_backup
          - path: /mnt/recordings
            name: 3cx_recordings
          - path: /var/log
            name: 3cx_log
        ports:
          - containerPort: 443
            clusterPort: 8443
          - containerPort: 5015
          - containerPort: 5060
          - containerPort: 5060
            protocol: udp
          - containerPort: 5061
          - containerPort: 5090
          - containerPort: 5090
            protocol: udp
    rules:
      ingressRules:
        - ports: 8443, 5015, 5060, 5061, 5090
        - ports: 5060, 5090
          protocol: udp
    
  - name: wso2
    containers:
      - image: wso2/wso2am:latest
        name: wso2am
        ports:
          - containerPort: 8280
          - containerPort: 8243
          - containerPort: 9443
          - containerPort: 5005
      - image: wso2/wso2mi:lates
        name: wso2mi
        ports:
          - containerPort: 8290
          - containerPort: 8253
          - containerPort: 9164
    rules:
      ingressRules:
        - ports: 8280, 8243, 9443, 5005, 8290, 8253, 9164
