---

_apps_deploying:
  - name: mariadb
    containers:
      - image: mariadb:10.3
        envVars:
          - name: MYSQL_ROOT_PASSWORD
            value: MotDePasseEnClair!
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress
          - name: MYSQL_PASSWORD
            value: epsi2022
        volumes:
          - path: /var/lib/mysql
        ports:
          - containerPort: 3306
    rules:
      ingressRules:
        - ports: 3306
          allowFrom: wordpress-deployment

  - name: wordpress
    replicas: 2
    exposed: True
    containers:
      - image: wordpress:latest
        envVars:
          - name: WORDPRESS_DB_HOST
            value: mariadb-service
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: epsi2022
        volumes:
          - name: wordpress-site
            path: /var/www/html
        ports:
          - containerPort: 80
            nodePort: 32001
    rules:
      ingressRules:
        - ports: 32001
    
  - name: wso2
    replicas: 2
    exposed: True
    containers:
      - image: wso2/wso2am:latest
        name: wso2am
        ports:
          - containerPort: 8280
            nodePort: 32007
          - containerPort: 8243
            nodePort: 32008
          - containerPort: 9443
            nodePort: 32009
          - containerPort: 5005
            nodePort: 32010
      - image: wso2/wso2mi:latest
        name: wso2mi
        ports:
          - containerPort: 8290
            nodePort: 32011
          - containerPort: 8253
            nodePort: 32012
          - containerPort: 9164
            nodePort: 32013
    rules:
      ingressRules:
        - ports: 32007, 32008, 32009, 32010, 32011, 32012, 32013