---

_apps_deploying:
  - name: mysql
    containers:
      - image: mysql:latest
        envVars:
          - name: MYSQL_ROOT_PASSWORD
            value: MotDePasseEnClair!
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress
          - name: MYSQL_PASSWORD
            value: epsi2022
        ports:
          - containerPort: 3306
    rules:
      ingressRules:
        - ports: 3306
          allowFrom: wordpress-deployment

  - name: wordpress
    replicas: 2
    exposed: True
    containers:
      - image: wordpress:latest
        envVars:
          - name: WORDPRESS_DB_HOST
            value: mysql-service
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: epsi2022
        ports:
          - containerPort: 80
            nodePort: 32001
    rules:
      ingressRules:
        - ports: 32001

