---

_apps_deploying:
  - name: mariadb
    containers:
      - image: mariadb:10.3
        envVars:
          - name: MYSQL_ROOT_PASSWORD
            value: MotDePasseEnClair!
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress
          - name: MYSQL_PASSWORD
            value: epsi2022
        volumes:
          - path: /var/lib/mysql
        ports:
          - containerPort: 3306
    rules:
      ingressRules:
        - ports: 3306
          allowFrom: wordpress-deployment

  - name: wordpress
    replicas: 2
    exposed: True
    containers:
      - image: wordpress:latest
        envVars:
          - name: WORDPRESS_DB_HOST
            value: mariadb-service
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: epsi2022
        volumes:
          - name: wordpress-site
            path: /var/www/html
        ports:
          - containerPort: 80
            nodePort: 32001
    rules:
      ingressRules:
        - ports: 32001
    
  - name: wso2
    replicas: 2
    exposed: True
    containers:
      - image: wso2/wso2am:latest
        name: wso2am
        ports:
          - containerPort: 8280
            nodePort: 32007
          - containerPort: 8243
            nodePort: 32008
          - containerPort: 9443
            nodePort: 32009
          - containerPort: 5005
            nodePort: 32010
      - image: wso2/wso2mi:latest
        name: wso2mi
        ports:
          - containerPort: 8290
            nodePort: 32011
          - containerPort: 8253
            nodePort: 32012
          - containerPort: 9164
            nodePort: 32013
    rules:
      ingressRules:
        - ports: 32007, 32008, 32009, 32010, 32011, 32012, 32013
  
  - name: ipbx3cx
    exposed: True
    containers:
      - image: farfui/3cx:18.0.2.314
        volumes:
          - path: /var/log
            name: 3cx-log
        ports:
          - containerPort: 443
            nodePort: 32014
          - containerPort: 5015
            nodePort: 32015
          - containerPort: 5060
            nodePort: 32016
          - containerPort: 5060
            nodePort: 32017
            protocol: udp
          - containerPort: 5061
            nodePort: 32018
          - containerPort: 5090
            nodePort: 32019
          - containerPort: 5090
            nodePort: 32019
            protocol: udp
    rules:
      ingressRules:
        - ports: 32014, 32015, 32016, 32018, 32019
        - ports: 32017, 32019
          protocol: udp

  - name: vpn
    exposed: True
    containers:
      - image: linuxserver/openvpn-as:latest
        envVars:
          - name: TZ
            value: Europe/Paris
        ports:
          - containerPort: 943
            nodePort: 32020
          - containerPort: 9443
            nodePort: 32021
          - containerPort: 1194
            nodePort: 32022
            protocol: udp