---

- name: enable host to bind to floating ip
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-proxy-bind-floating-ip.conf
    line: net.ipv4.ip_nonlocal_bind = 1
    create: True
    owner: root
    group: root
  tags: keepalived
  register: _sys_config
  become: True

- name: apply system configuration
  ansible.builtin.command: sysctl --system
  when: _sys_config.changed
  tags: keepalived
  become: True

- name: install keepalived on nodes
  ansible.builtin.apt:
    name: keepalived
    state: present
  tags: keepalived
  become: True

- name: deploy keepalived configuration
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  tags: keepalived
  become: True

- name: enable service keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: True
  tags: keepalived
  become: True
