---

- name: install proxy on nodes
  ansible.builtin.apt:
    name: nginx
    state: present
  throttle: 1
  tags: proxy
  become: True

- name: start proxy service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: True
  tags: proxy
  become: True

- name: deploy crontask for proxy restart
  ansible.builtin.cron:
    name: "reload nginx proxy"
    job: "/bin/systemctl restart nginx.service"
    user: root
    hour: "0"
    minute: "0"
  tags: proxy
  become: True
