---

- name: create custom script directory
  ansible.builtin.file:
    path: /opt/cluster-scripts/
    state: directory
    recurse: True
  tags: letsencrypt_config
  become: True

- name: upload custom script to directory
  ansible.builtin.template:
    src: update-cert.j2
    dest: /opt/cluster-scripts/update-cert.sh
    mode: '0755'
  tags: letsencrypt_config
  become: True

- name: launch certificate creation
  ansible.builtin.shell: >-
    kubectl exec -n {{ admin_namespace }} -it \
    $(kubectl get pods -n {{ admin_namespace }} | grep certbot-deployment | cut -d " " -f1) -- \
    certbot certonly --standalone -n -d {{ site_fqdn }} -m {{ site_email }} --agree-tos {{ production_cluster | ternary('', '--test-cert') }}
  args:
    executable: /bin/bash
  register: result
  until: result.stdout.find("Successfully received certificate.") != -1
  retries: 12
  delay: 10
  changed_when: False
  tags:
    - letsencrypt_config
    - definitive

- name: add certificate renewal to crontab
  ansible.builtin.cron:
    name: "update certificates"
    user: root
    job: "/opt/cluster-scripts/update-cert.sh"
    hour: "0"
    minute: "0"
  tags: letsencrypt_config
  become: True
