---

- name: create custom script directory
  ansible.builtin.file:
    path: /opt/cluster-scripts/
    state: directory
    recurse: True
  tags: letsencrypt
  become: True

- name: upload custom scripts to directory
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/opt/cluster-scripts/{{ item }}.sh"
    mode: '0755'
  loop: "{{ _scripts }}"
  tags: letsencrypt
  become: True

- name: launch certificate creation
  ansible.builtin.command: /opt/cluster-scripts/create-cert.sh
  register: result
  until: result.stdout.find("Successfully received certificate.") != -1
  retries: 12
  delay: 10
  changed_when: False
  tags:
    - letsencrypt
    - definitive
