---

- name: configure kubernetes cluster
  hosts: all

  roles:
    - role: install_kubernetes_requirements

    - role: install_kubernetes
      calico_version: "{{ play_calico_version }}"

    - role: configure_cluster
      calico_version: "{{ play_calico_version }}"

    - role: install_nfs
