---

- name: deploy services on cluster
  hosts: kubernetes

  roles:
    - role: kubernetes_deployment
      kubernetes_deployment_conf: "{{ run_kubernetes_deployment_conf }}"
      kubernetes_deployment_proxy: "{{ run_proxy_floating_ip }}"
