---

- name: patch system
  hosts: kubernetes
  serial: 1
  roles:
    - role: system_patching

- name: configure kubernetes cluster
  hosts: kubernetes
  vars:
    calico_version: v3.24.1
    admin_namespace: "{{ play_admin_namespace }}"
    proxy_floating_ip: "{{ run_proxy_floating_ip }}"
    site_fqdn: "{{ run_site_fqdn }}"

  roles:
    - role: kubernetes_install

    - role: kubernetes_cluster
      kubernetes_data_dev: "{{ run_data_dev }}"

    - role: nfs_mount
      nfs_mount: "{{ play_nfs_configuration }}"

    - role: proxy_install

    - role: kubernetes_deployment
      https_enabled: False
      tags: definitive
    
    - role: letsencrypt_config
      production_cluster: "{{ run_production_cluster | default(False) }}"
      site_email: "{{ run_site_email }}"
      run_once: True
      when:
        - "'control-plane' in group_names"
        - "run_https_enabled | default(True)"
