---

- name: configure kubernetes cluster
  hosts: all

  roles:
    - kubernetes_system_requirements
    - install_docker
    - install_kubernetes
    - configure_cluster

    - role: install_nfs_server
      when: cloud_function == "master"

    - role: kubernetes_deployment
      when: cloud_function == "master"
