---

- name: configure kubernetes cluster
  hosts: all

  roles:
    - kubernetes_system_requirements
    - install_docker
    - install_kubernetes
    - configure_cluster
    - install_nfs

    - role: kubernetes_deployment
      when: cloud_function == "master"
