---

- name: deploy services on cluster
  hosts: kubernetes

  roles:
    - role: kubernetes_deployment
      kubernetes_deployment_conf: "{{ run_kubernetes_deployment_conf }}"
      proxy_floating_ip: "{{ run_proxy_floating_ip }}"
      site_fqdn: "{{ run_site_fqdn }}"
      admin_namespace: "{{ play_admin_namespace }}"
      https_enabled: "{{ run_https_enabled | default(True) }}"
