---

- name: configure kubernetes cluster
  hosts: all

  roles:
    - kubernetes_system_requirements
    - install_docker
    - install_kubernetes

    - role: configure_cluster
      when: cloud_function == "master"

    - role: install_nfs_server
      when: cloud_function == "master"
    
    - start_docker

    - role: kubernetes_deployment
      when: cloud_function == "master"
