---

- name: configure kubernetes cluster
  hosts: all

  roles:
    - role: kubernetes_system_requirements

    - role: install_docker

    - role: install_kubernetes
      calico_version: "{{ play_calico_version }}"

    - role: configure_cluster
      calico_version: "{{ play_calico_version }}"

    - role: install_nfs

    - role: kubernetes_deployment
      when: cloud_function == "master"
