---

- name: copy default network policy on master
  copy:
    src: default_policy.yml
    dest: /tmp/default-network-policy.yml
  tags: deployment
  become: True

- name: apply default network policy to cluster
  shell: calicoctl apply -f /tmp/default-network-policy.yml
  args:
    executable: /bin/bash
  tags: deployment

- name: delete policy configuration file
  file:
    path: /tmp/default-network-policy.yml
    state: absent
  tags: deployment
  become: True

- name: create services configuration directory
  file:
    path: /tmp/k8s-configurations/app
    state: directory
    owner: svcansible
    group: ansible
  tags: deployment
  become: True

- name: create policies configuration directory
  file:
    path: /tmp/k8s-configurations/policies
    state: directory
    owner: svcansible
    group: ansible
  tags: deployment
  become: True

- name: create services configuration files
  template:
    src: application.j2
    dest: "/tmp/k8s-configurations/app/{{ item.name }}.yml"
  loop: "{{ _apps_deploying }}"
  loop_control:
    label: "{{ item.name }}"
  tags: deployment

- name: create variable data directories
  set_fact:
    run_directories: "{{ run_directories | default([]) + [{ 'name': item.0.name, 'volumes': item.1.volumes }] }}"
  with_subelements:
    - "{{ _apps_deploying }}"
    - containers
  loop_control:
    label: "{{ item.0.name }}"
  when: item.1.volumes is defined
  tags: deployment

- name: create data directory for volumes
  file:
    path: "/data/{{ item.0.name }}/{{ item.1.name | default(item.1.path | replace('/', '')) | lower }}"
    state: directory
    recurse: True
  with_subelements:
    - "{{ run_directories }}"
    - volumes
  loop_control:
    label: "{{ item.0.name }}/{{ item.1.name | default(item.1.path | replace('/', '')) | lower }}"
  tags: deployment

- name: create policies configuration files
  template:
    src: network_policy.j2
    dest: "/tmp/k8s-configurations/policies/{{ item.name }}.yml"
  loop: "{{ _apps_deploying }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.rules is defined
  tags: deployment

- name: create services on cluster
  shell: "kubectl create -f /tmp/k8s-configurations/app/{{ item.name }}.yml"
  args:
    executable: /bin/bash
  loop: "{{ _apps_deploying }}"
  loop_control:
    label: "{{ item.name }}"
  tags: deployment

- name: apply services network policies
  shell: calicoctl apply -f /tmp/k8s-configurations/policies/
  args:
    executable: /bin/bash
  tags: deployment

- name: delete configuration directory
  file:
    path: /tmp/k8s-configurations
    state: absent
  tags: deployment
  become: True