---

- name: configure services and rules
  ansible.builtin.import_tasks: _configuration.yml
  when: "'control-plane' in group_names and 'nfs-server' in group_names"

- name: reload haproxy to get new configuration
  ansible.builtin.service:
    name: haproxy
    state: reloaded
    enabled: True
  when: "'nodes' in group_names"
  tags: deployment
  become: True
