---

- name: create nfs-group
  group:
    name: "nfs-group"
    gid: 1200
    state: present
  tags: nfs
  become: True

- name: add svcansible to nfs-group
  user:
    name: svcansible
    groups: "nfs-group"
    append: True
  tags: nfs
  become: True

- name: create data directory
  file:
    path: /data
    state: directory
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: set permissions on data directory
  shell: >-
    chmod 2777 /data \
    && chown svcansible:nfs-group /data
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: create filesystem on seperate disk
  filesystem:
    fstype: ext4
    dev: /dev/sdb
  when: cloud_function == "master"
  tags: nfs, definitive
  become: True

- name: removing unwanted data
  shell: tune2fs -m 0 /dev/sdb
  args:
    executable: /bin/bash
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: mount partition on filesystem
  mount:
    src: /dev/sdb
    path: /data
    state: mounted
    fstype: ext4
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: install nfs packages on server
  apt:
    name: nfs-kernel-server
    state: present
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: install nfs packages on worker
  apt:
    name: nfs-common
    state: present
  when: cloud_function == "worker"
  tags: nfs
  become: True

- name: add network to exports
  lineinfile:
    line: "/data {{ ansible_host.split('.')[0] }}.{{ ansible_host.split('.')[1] }}.0.0/16(rw,async,no_root_squash,no_subtree_check)"
    path: /etc/exports
    create: True
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: start nfs server
  service:
    name: nfs-server
    enabled: True
    state: restarted
  when: cloud_function == "master"
  tags: nfs
  become: True