---

- name: create nfs-group
  ansible.builtin.group:
    name: "nfs-group"
    gid: 1200
    state: present
  tags: nfs
  become: True

- name: add svcansible to nfs-group
  ansible.builtin.user:
    name: svcansible
    groups: "nfs-group"
    append: True
  tags: nfs
  become: True

- name: create data directory
  ansible.builtin.file:
    path: /data
    state: directory
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: create filesystem on seperate disk
  ansible.builtin.filesystem:
    fstype: ext4
    dev: /dev/sdb
  when: cloud_function == "master"
  tags:
    - nfs
    - partitions
    - definitive
  become: True

- name: removing unwanted data
  ansible.builtin.command: tune2fs -m 0 /dev/sdb
  when: cloud_function == "master"
  tags:
    - nfs
    - partitions
  become: True

- name: mount partition on filesystem
  ansible.builtin.mount:
    src: /dev/sdb
    path: /data
    state: mounted
    fstype: ext4
  when: cloud_function == "master"
  tags:
    - nfs
    - partitions
  become: True

- name: set permissions on data directory
  ansible.builtin.file:
    path: /data
    state: directory
    owner: svcansible
    group: nfs-group
    mode: "2777"
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: install nfs packages on server
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: install nfs packages on worker
  ansible.builtin.apt:
    name: nfs-common
    state: present
  when: cloud_function == "worker"
  tags: nfs
  become: True

- name: add network to exports
  ansible.builtin.lineinfile:
    line: "/data {{ ansible_host.split('.')[0] }}.{{ ansible_host.split('.')[1] }}.0.0/16(rw,async,no_root_squash,no_subtree_check)"
    path: /etc/exports
    create: True
  when: cloud_function == "master"
  tags: nfs
  become: True

- name: start nfs server
  ansible.builtin.service:
    name: nfs-server
    enabled: True
    state: restarted
  when: cloud_function == "master"
  tags: nfs
  become: True