---

- name: add kubernetes key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags: kubernetes
  become: True

- name: add kubernetes repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
  tags: kubernetes
  become: True

- name: install kubernetes packages
  ansible.builtin.apt:
    name: "{{ _kubernetes_packages }}"
    state: present
    update_cache: True
  tags: kubernetes
  become: True

- name: install calicoctl
  ansible.builtin.get_url:
    url: "https://github.com/projectcalico/calico/releases/download/{{ calico_version }}/calicoctl-linux-amd64"
    dest: /usr/local/bin
    mode: "0555"
  tags: kubernetes
  become: True

- name: renaming calico binaries
  ansible.builtin.command: mv /usr/local/bin/calicoctl-linux-amd64 /usr/local/bin/calicoctl
  tags: kubernetes
  become: True

- name: configure node ip
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    line: "KUBELET_EXTRA_ARGS=--node-ip={{ ansible_host }} --cgroup-driver=systemd"
    create: True
  tags: kubernetes
  become: True

- name: restart kubelet
  ansible.builtin.service:
    name: kubelet
    daemon_reload: True
    state: restarted
  tags: kubernetes
  become: True