---

- name: initialize kubernetes cluster
  ansible.builtin.command: >-
    kubeadm init --apiserver-advertise-address={{ ansible_host }} \
    --apiserver-cert-extra-sans={{ ansible_host }}  \
    --node-name {{ inventory_hostname | lower }} \
    --pod-network-cidr=172.16.0.0/16
  tags: definitive
  become: True

- name: create svcansible kubernetes config folder on master
  ansible.builtin.file:
    path: /home/svcansible/.kube
    state: directory

- name: copy kubernetes admin config in svcansible config folder
  ansible.builtin.copy:
    remote_src: True
    src: /etc/kubernetes/admin.conf
    dest: /home/svcansible/.kube/config
    owner: svcansible
    group: ansible
  become: True

- name: wait for cluster availability
  ansible.builtin.command: kubectl cluster-info
  register: result
  until: result.stdout.find("is running at") != -1
  retries: 12
  delay: 10
  changed_when: False

- name: get calico manifest
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"
    dest: /tmp

- name: install calico network
  ansible.builtin.shell: >-
    sed -i "s/192.168./172.16./g" /tmp/calico.yaml \
    && kubectl apply -f /tmp/calico.yaml
  args:
    executable: /bin/bash
  tags: network

- name: removing calico configuration file
  ansible.builtin.file:
    path: /tmp/calico.yaml
    state: absent
