---

- name: check for cluster availability
  ansible.builtin.command: kubectl cluster-info
  register: result
  until: result.stdout.find("is running at") != -1
  retries: 12
  delay: 10
  changed_when: False

- name: check if worker is already joined
  ansible.builtin.shell: kubectl get nodes --all-namespaces --no-headers | cut -d " " -f1
  args:
    executable: /bin/bash
  register: cluster_server

- name: join cluster command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: run_join_command
  become: True

- name: save command in temporary file
  ansible.builtin.lineinfile:
    path: "/tmp/{{ client_id | lower }}.sh"
    line: "{{ run_join_command.stdout }}"
    create: True
  delegate_to: localhost
  become: True