---

- name: create data directory
  ansible.builtin.file:
    path: /data
    state: directory
  tags: cluster
  become: True

- name: create filesystem on seperate disk
  ansible.builtin.filesystem:
    fstype: ext4
    dev: "{{ kubernetes_data_dev }}"
  tags:
    - cluster
    - partitions
    - definitive
  become: True

- name: removing unwanted data
  ansible.builtin.command: "tune2fs -m 0 {{ kubernetes_data_dev }}"
  tags:
    - cluster
    - partitions
  become: True

- name: mount partition on filesystem
  ansible.builtin.mount:
    src: "{{ kubernetes_data_dev }}"
    path: /data
    state: mounted
    fstype: ext4
  tags:
    - cluster
    - partitions
  become: True

- name: set permissions on data directory
  ansible.builtin.file:
    path: /data
    state: directory
    owner: svcansible
    group: nfs-group
    mode: "2777"
  tags: cluster
  become: True

- name: install nfs packages on server
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  tags: cluster
  become: True

- name: add network to exports
  ansible.builtin.lineinfile:
    line: "/data {{ ansible_host.split('.')[0] }}.{{ ansible_host.split('.')[1] }}.0.0/16(rw,async,no_root_squash,no_subtree_check)"
    path: /etc/exports
    create: True
  tags: cluster
  become: True

- name: start nfs server
  ansible.builtin.service:
    name: nfs-server
    enabled: True
    state: restarted
  tags: cluster
  become: True
