---

- name: start a kubernetes cluster
  ansible.builtin.import_tasks: _cluster_init.yml
  when: "'control-plane' in group_names"
  tags:
    - kubernetes_cluster
    - init

- name: start a kubernetes cluster
  ansible.builtin.import_tasks: _cluster_join.yml
  when: "'control-plane' in group_names"
  tags:
    - kubernetes_cluster
    - join

- name: copy join command on workers
  ansible.builtin.copy:
    src: "/tmp/{{ client_id | lower }}.sh"
    dest: /tmp/join_command.sh
  when: "'nodes' in group_names"
  tags:
    - kubernetes_cluster
    - join
    - definitive
  become: True

- name: append hostname to script
  ansible.builtin.command: "sed -i '/kubeadm/ s/$/ --node-name {{ inventory_hostname | lower }}/' /tmp/join_command.sh"
  when: "'nodes' in group_names"
  tags:
    - kubernetes_cluster
    - join
    - definitive
  become: True

- name: remove command file on localhost
  ansible.builtin.file:
    path: "/tmp/{{ client_id | lower }}.sh"
    state: absent
  delegate_to: localhost
  when: "'control-plane' in group_names"
  tags:
    - kubernetes_cluster
    - worker
  become: True

- name: launch joining command on workers
  ansible.builtin.command: bash /tmp/join_command.sh
  when: "'nodes' in group_names"
  tags:
    - kubernetes_cluster
    - worker
    - join
    - definitive
  become: True

- name: remove command file on workers
  ansible.builtin.file:
    path: /tmp/join_command.sh
    state: absent
  when: "'nodes' in group_names"
  tags:
    - kubernetes_cluster
    - worker
  become: True

- name: create endpoints configuration files
  ansible.builtin.import_tasks: _endpoints_config.yml
  when: "'control-plane' in group_names"
  tags: kubernetes_cluster

- name: create nfs-group
  ansible.builtin.group:
    name: "nfs-group"
    gid: 1200
    state: present
  tags: kubernetes_cluster
  become: True

- name: add svcansible to nfs-group
  ansible.builtin.user:
    name: svcansible
    groups: "nfs-group"
    append: True
  tags: kubernetes_cluster
  become: True

- name: install nfs packages on worker
  ansible.builtin.apt:
    name: nfs-common
    state: latest
  when: "'nodes' in group_names"
  tags: kubernetes_cluster
  become: True

- name: install nfs server
  ansible.builtin.import_tasks: _nfs_config.yml
  when: "'nfs-server' in group_names"
  tags: kubernetes_cluster
